/**
 * Prewritten campaign content + Pacific-time due-selection for the autonomous publisher.
 *
 * The bundle is GENERATED by tools/authority-campaign-publisher/prebake_worker_content.py,
 * which runs the proven, hash-checked Python renderer/discovery once per signed day. The
 * Worker never re-renders — it commits `article_html` verbatim and re-applies the four
 * `surfaces` insertions against live repo state.
 */
import bundleJson from './content.generated.json'

export interface Surface {
  /** Repo-relative file the fragment is inserted into. */
  path: string
  /** Structural anchor the insertion is positioned against. */
  anchor: string
  /** Whether the anchor is matched together with the file's trailing newline. */
  anchor_trailing_newline: boolean
  /** Insert the fragment after the anchor, or before it (sitemap `</urlset>`). */
  position: 'after' | 'before'
  /** Emit one extra newline before the fragment (home-rail card). */
  prepend_newline: boolean
  /** Fragment as individual lines; joined with the live file's own newline. */
  fragment_lines: string[]
  /** href/URL whose occurrence count encodes idempotency. */
  marker: string
  /** Occurrence count of `marker` that means "already published" (skip). */
  present_count: number
}

export interface LinkedInContent {
  commentary: string
  title: string
  alt_text: string
  first_comment: string
  card_path: string | null
}

export interface CampaignDay {
  campaign_id: string
  /** Civil publish date in America/Los_Angeles, YYYY-MM-DD. */
  publish_date: string
  /** Offset-aware instant the blog lane opens (05:00 Pacific). */
  blog_at: string
  /** Offset-aware instant the LinkedIn lane opens. */
  linkedin_at: string
  blog_path: string
  blog_url: string
  content_sha256: string
  article_html: string
  surfaces: Surface[]
  linkedin: LinkedInContent
}

interface Bundle {
  note: string
  manifest_sha256: string
  items: CampaignDay[]
}

// The generated JSON is structurally validated at bake time; cast through unknown so the
// Worker builds against the compact interface above rather than the JSON's literal type.
export const CONTENT = bundleJson as unknown as Bundle

/** Civil date (YYYY-MM-DD) in America/Los_Angeles for an instant. */
export function pacificDate(now: Date): string {
  return new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Los_Angeles' }).format(now)
}

/** The campaign day scheduled for this Pacific date, if any. */
export function dayFor(pacificYmd: string): CampaignDay | undefined {
  return CONTENT.items.find((item) => item.publish_date === pacificYmd)
}

/** LinkedIn hard cutoff: 08:01 Pacific on the item's publish date (mirrors run_due). */
export function linkedinCutoffMs(day: CampaignDay): number {
  // linkedin_at already carries the correct DST offset for that calendar date.
  const offset = day.linkedin_at.slice(-6) // e.g. "-07:00"
  return Date.parse(`${day.publish_date}T08:01:00${offset}`)
}
